export 'dart:async';
export 'dart:convert';
export 'dart:io' hide HeaderValue;

export 'package:flutter/cupertino.dart' show CupertinoAlertDialog;
export 'package:flutter/material.dart';
export 'package:flutter/scheduler.dart' hide Priority;
export 'package:flutter/services.dart';
export 'package:start_up_workspace/resources/mixins/responsive_design_breakpoints.dart';
export 'package:start_up_workspace/resources/widgets/responsive_design.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart';

export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:flutter_dotenv/flutter_dotenv.dart';
export 'package:flutter_gen/gen_l10n/app_localizations.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:get/get.dart';
export 'package:in_app_review/in_app_review.dart';
export 'package:internet_connection_checker/internet_connection_checker.dart';
export 'package:intl/intl.dart' hide TextDirection;
export 'package:loading_plus/loading_plus.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:share_plus/share_plus.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:upgrader/upgrader.dart' hide ambiguate;
export 'package:url_launcher/url_launcher.dart';

export 'package:start_up_workspace/main.dart';
export 'package:start_up_workspace/models/user_model.dart';
export 'package:start_up_workspace/modules/auth/binding/auth_binding.dart';
export 'package:start_up_workspace/modules/auth/controller/auth_controller.dart';
export 'package:start_up_workspace/modules/auth/view/auth_view.dart';
export 'package:start_up_workspace/modules/connection_error/binding/connection_error_binding.dart';
export 'package:start_up_workspace/modules/connection_error/controller/connection_error_controller.dart';
export 'package:start_up_workspace/modules/connection_error/view/connection_error_view.dart';
export 'package:start_up_workspace/modules/home/controller/home_controller.dart';
export 'package:start_up_workspace/modules/home/view/home_view.dart';
export 'package:start_up_workspace/modules/home/widgets/drawer_home.dart';
export 'package:start_up_workspace/modules/navigation/binding/navigation_binding.dart';
export 'package:start_up_workspace/modules/navigation/controller/navigation_controller.dart';
export 'package:start_up_workspace/modules/navigation/view/navigation_view.dart';
export 'package:start_up_workspace/modules/settings/binding/settings_binding.dart';
export 'package:start_up_workspace/modules/settings/controller/settings_controller.dart';
export 'package:start_up_workspace/modules/settings/view/settings_view.dart';
export 'package:start_up_workspace/modules/splash/binding/splash_binding.dart';
export 'package:start_up_workspace/modules/splash/controller/splash_controller.dart';
export 'package:start_up_workspace/modules/splash/view/splash_view.dart';
export 'package:start_up_workspace/repositories/auth/auth_repository.dart';
export 'package:start_up_workspace/resources/components.dart';
export 'package:start_up_workspace/resources/enums/auth_type.dart';
export 'package:start_up_workspace/resources/managers/assets_manager.dart';
export 'package:start_up_workspace/resources/managers/constants_manager.dart';
export 'package:start_up_workspace/resources/managers/exception_manager.dart';
export 'package:start_up_workspace/resources/managers/fonts_manager.dart';
export 'package:start_up_workspace/resources/managers/routes_manager.dart';
export 'package:start_up_workspace/resources/managers/validators_manager.dart';
export 'package:start_up_workspace/resources/services/encryption_service.dart';
export 'package:start_up_workspace/resources/services/master_functions_service.dart';
export 'package:start_up_workspace/resources/services/notification_service.dart';
export 'package:start_up_workspace/resources/services/shared_prefs_service.dart';
export 'package:start_up_workspace/resources/theme/colors_manager.dart';
export 'package:start_up_workspace/resources/theme/custom_theme_data.dart';
export 'package:start_up_workspace/resources/theme/theme_manager.dart';
export 'package:start_up_workspace/resources/widgets/main_app_bar.dart';
export 'package:start_up_workspace/resources/widgets/main_button.dart';
export 'package:start_up_workspace/resources/widgets/main_text_field.dart';
export 'package:start_up_workspace/resources/widgets/scale_text.dart';
export 'package:start_up_workspace/resources/widgets/upgrade_dialog.dart';
